version: '3.8'

services:
  app:
    build: .
    container_name: clevernote_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - clevernote_net

  web:
    image: nginx:latest
    container_name: clevernote_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - clevernote_net

  db:
    image: mysql:8
    container_name: clevernote_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: clevernote
      MYSQL_USER: clevernote
      MYSQL_PASSWORD: JBqPIC9cyLMg8tq^
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - clevernote_net

  redis:
    image: redis:alpine
    container_name: clevernote_redis
    restart: always
    networks:
      - clevernote_net

  queue:
    build: .
    container_name: clevernote_queue
    restart: always
    working_dir: /var/www
    command: ["php", "artisan", "queue:work", "--tries=3"]
    depends_on:
      - redis
    networks:
      - clevernote_net

networks:
  clevernote_net:

volumes:
  db_data:
