version: '3.8'

services:
  app:
    build: .
    ports:
      - "5173:5173"
    container_name: clevernote_app
    restart: always
    working_dir: /var/www/clevernote
    volumes:
      - .:/var/www/clevernote
    depends_on:
      - db
      - redis
    networks:
      - clevernote_net

  web:
    image: nginx:latest
    container_name: clevernote_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/clevernote
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - clevernote_net

  db:
    image: mysql:8
    container_name: clevernote_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - clevernote_net

  redis:
    image: redis:alpine
    container_name: clevernote_redis
    restart: always
    networks:
      - clevernote_net

  queue:
    build: .
    volumes:
      - .:/var/www/clevernote
    container_name: clevernote_queue
    restart: always
    working_dir: /var/www/clevernote
    command: ["php", "artisan", "queue:work", "--tries=3"]
    depends_on:
      - redis
    networks:
      - clevernote_net

networks:
  clevernote_net:

volumes:
  db_data:
